---
abstract: 'add a pod section with multiple authors, copyright owners and licenses in a file basis'
author:
  - 'Carnë Draug <cdraug@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Section-Legal-Complicated
requires:
  List::MoreUtils: 0
  Module::Load: 0
  Moose: 0
  MooseX::Types::Moose: 0
  Pod::Elemental::Element::Nested: 0
  Pod::Elemental::Element::Pod5::Ordinary: 0
  Pod::Weaver::Role::Section: 0
  Software::License: 0
  namespace::autoclean: 0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/carandraug/pod-weaver-section-legal-complicated/issues
  homepage: https://github.com/carandraug/pod-weaver-section-legal-complicated
  repository: git://github.com/carandraug/pod-weaver-section-legal-complicated.git
version: 1.21
x_authority: cpan:CDRAUG
